// Copyright 2026 The Dart package:osqp authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:osqp/osqp.dart')
library;

import 'dart:ffi' as ffi;

/// Free an OSQPCodegenDefines object.
///
/// @note Not available in embedded mode (requires free)
///
/// @param defs The defines object to free
@ffi.Native<ffi.Void Function(ffi.Pointer<OSQPCodegenDefines>)>()
external void OSQPCodegenDefines_free(ffi.Pointer<OSQPCodegenDefines> defs);

/// Allocate a new OSQPCodegenDefines object with the default options.
///
/// @note Not available in embedded mode (requires malloc)
///
/// @return Pointer to new codegen defines object, or null on error
@ffi.Native<ffi.Pointer<OSQPCodegenDefines> Function()>()
external ffi.Pointer<OSQPCodegenDefines> OSQPCodegenDefines_new();

/// Allocates a new Compressed-Column-Sparse (CSC) diagonal matrix with a given value.
///
/// This will start populating at the upper-left element and continue down the main diagonal
/// until either the last row or column (in the case of non-square matrices).
///
/// @note Not available in embedded mode (requires malloc)
///
/// @param  m      Number of rows
/// @param  n      Number of columns
/// @param  scalar Scalar value to put on the diagonal
/// @return        Pointer to new CSC matrix, or null on error
@ffi.Native<ffi.Pointer<OSQPCscMatrix> Function(OSQPInt, OSQPInt, OSQPFloat)>()
external ffi.Pointer<OSQPCscMatrix> OSQPCscMatrix_diag_scalar(
  int m,
  int n,
  double scalar,
);

/// Allocates a new Compressed-Column-Sparse (CSC) diagonal matrix with given values on the diagonal.
///
/// This will start populating at the upper-left element and continue down the main diagonal
/// until either the last row or column (in the case of non-square matrices).
///
/// @note Not available in embedded mode (requires malloc)
///
/// @param  m    Number of rows
/// @param  n    Number of columns
/// @param  vals Values to put on the diagonal - length min(n,m)
/// @return      Pointer to new CSC matrix, or null on error
@ffi.Native<
  ffi.Pointer<OSQPCscMatrix> Function(OSQPInt, OSQPInt, ffi.Pointer<OSQPFloat>)
>()
external ffi.Pointer<OSQPCscMatrix> OSQPCscMatrix_diag_vec(
  int m,
  int n,
  ffi.Pointer<OSQPFloat> vals,
);

/// Free a CSC matrix object allocated by @ref OSQPCscMatrix_new.
///
/// @note This function will only free the internal @ref OSQPCscMatrix.x, @ref OSQPCscMatrix.p,
/// @ref OSQPCscMatrix.i arrays if the @ref OSQPCscMatrix.owned variable is set to `1`, otherwise
/// only the outer CSC wrapper is free'd.
///
/// @note Not available in embedded mode (requires free)
///
/// @param mat Matrix to free
@ffi.Native<ffi.Void Function(ffi.Pointer<OSQPCscMatrix>)>()
external void OSQPCscMatrix_free(ffi.Pointer<OSQPCscMatrix> mat);

/// Allocates a new Compressed-Column-Sparse (CSC) identity with 1s on the diagonal.
///
/// @note Not available in embedded mode (requires malloc)
///
/// @param  m Number of rows/columns
/// @return   Pointer to new CSC matrix, or null on error
@ffi.Native<ffi.Pointer<OSQPCscMatrix> Function(OSQPInt)>()
external ffi.Pointer<OSQPCscMatrix> OSQPCscMatrix_identity(int m);

/// Allocates a new Compressed-Column-Sparse (CSC) matrix from existing arrays.
///
/// This will malloc the new matrix structure, but use the arrays passed in as the
/// backing data for the matrix (e.g. not copy the actual matrix data, just reference
/// the existing data.)
///
/// @note Not available in embedded mode (requires malloc)
///
/// @param  m     Number of rows
/// @param  n     number of columns
/// @param  nzmax Maximum number of nonzero elements
/// @param  x     Vector of data
/// @param  i     Vector of row indices
/// @param  p     Vector of column pointers
/// @return       Pointer to new CSC matrix, or null on error
@ffi.Native<
  ffi.Pointer<OSQPCscMatrix> Function(
    OSQPInt,
    OSQPInt,
    OSQPInt,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPInt>,
    ffi.Pointer<OSQPInt>,
  )
>()
external ffi.Pointer<OSQPCscMatrix> OSQPCscMatrix_new(
  int m,
  int n,
  int nzmax,
  ffi.Pointer<OSQPFloat> x,
  ffi.Pointer<OSQPInt> i,
  ffi.Pointer<OSQPInt> p,
);

/// Populates a Compressed-Column-Sparse matrix from existing data arrays.
/// This will just assign the pointers - no malloc or copying is done.
///
/// @param  M     Matrix pointer
/// @param  m     First dimension
/// @param  n     Second dimension
/// @param  nzmax Maximum number of nonzero elements
/// @param  x     Vector of data
/// @param  i     Vector of row indices
/// @param  p     Vector of column pointers
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<OSQPCscMatrix>,
    OSQPInt,
    OSQPInt,
    OSQPInt,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPInt>,
    ffi.Pointer<OSQPInt>,
  )
>()
external void OSQPCscMatrix_set_data(
  ffi.Pointer<OSQPCscMatrix> M,
  int m,
  int n,
  int nzmax,
  ffi.Pointer<OSQPFloat> x,
  ffi.Pointer<OSQPInt> i,
  ffi.Pointer<OSQPInt> p,
);

/// Allocates a new Compressed-Column-Sparse (CSC) matrix with zero entries.
///
/// This matrix will contain all structural zeros, so no non-zero elements will be present.
///
/// @note Not available in embedded mode (requires malloc)
///
/// @param  m Number of rows
/// @param  n Number of columns
/// @return   Pointer to new CSC matrix, or null on error
@ffi.Native<ffi.Pointer<OSQPCscMatrix> Function(OSQPInt, OSQPInt)>()
external ffi.Pointer<OSQPCscMatrix> OSQPCscMatrix_zeros(int m, int n);

/// Free an OSQPSettings object.
///
/// @note Not available in embedded mode (requires free)
///
/// @param settings The settings object to free
@ffi.Native<ffi.Void Function(ffi.Pointer<OSQPSettings>)>()
external void OSQPSettings_free(ffi.Pointer<OSQPSettings> settings);

/// Allocate a new OSQPSettings object with the default settings.
///
/// @note Not available in embedded mode (requires malloc)
///
/// @return Pointer to new settings object, or null on error
@ffi.Native<ffi.Pointer<OSQPSettings> Function()>()
external ffi.Pointer<OSQPSettings> OSQPSettings_new();

@ffi.Native<ffi.Pointer<ffi.Pointer<ffi.Char>>>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> OSQP_ERROR_MESSAGE;

@ffi.Native<ffi.Pointer<ffi.Pointer<ffi.Char>>>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> OSQP_STATUS_MESSAGE;

/// Compute internal data structures needed for calculation of the adjoint derivatives of P/q/A/l/u.
///
/// @note An optimal solution must be obtained before calling this function.
///
/// @param[in] solver Solver
/// @param[in] dx     Vector of dx values (observed - true) of length n
/// @param[in] dy     Vector of dy values (observed - true) of length m
/// @return           Exitflag for errors (0 if no errors)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
  )
>()
external int osqp_adjoint_derivative_compute(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPFloat> dx,
  ffi.Pointer<OSQPFloat> dy,
);

/// Calculate adjoint derivatives of P/A.
///
/// @note @c osqp_adjoint_derivative_compute must be called first.
///
/// @param[in]  solver Solver
/// @param[out] dP     Matrix of dP values (n x n)
/// @param[out] dA     Matrix of dA values (m x n)
/// @return            Exitflag for errors (0 if no errors; dP, dA are filled in)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPCscMatrix>,
    ffi.Pointer<OSQPCscMatrix>,
  )
>()
external int osqp_adjoint_derivative_get_mat(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPCscMatrix> dP,
  ffi.Pointer<OSQPCscMatrix> dA,
);

/// Calculate adjoint derivatives of q/l/u.
///
/// @note @c osqp_adjoint_derivative_compute must be called first.
///
/// @param[in]  solver Solver
/// @param[out] dq     Vector of dq values of length n
/// @param[out] dl     Matrix of dl values of length m
/// @param[out] du     Matrix of du values of length m
/// @return            Exitflag for errors (0 if no errors; dq, dl, du are filled in)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
  )
>()
external int osqp_adjoint_derivative_get_vec(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPFloat> dq,
  ffi.Pointer<OSQPFloat> dl,
  ffi.Pointer<OSQPFloat> du,
);

/// Return the capabilities of the OSQP solver.
///
/// @return
@ffi.Native<OSQPInt Function()>()
external int osqp_capabilities();

/// Cleanup workspace by deallocating memory
///
/// This function is not used in code generation
/// @param  solver Solver
/// @return        Exitflag for errors (0 if no errors)
@ffi.Native<OSQPInt Function(ffi.Pointer<OSQPSolver>)>()
external int osqp_cleanup(ffi.Pointer<OSQPSolver> solver);

/// Generate source files with a statically allocated OSQPSolver structure.
///
/// @note @c osqp_setup must be called before a problem can be code generated.
///
/// @param  solver     Solver
/// @param  output_dir Path to directory to output the files to.
/// This string must include the trailing directory separator, and
/// an empty string means output to the current directory.
/// @param  prefix     String prefix for the variables and generated files.
/// @param  defines    The defines to use in the generated code.
/// @return            Exitflag for errors (0 if no errors)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<OSQPCodegenDefines>,
  )
>()
external int osqp_codegen(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<ffi.Char> output_dir,
  ffi.Pointer<ffi.Char> prefix,
  ffi.Pointer<OSQPCodegenDefines> defines,
);

/// Cold start workspace variables xz and y
/// @param solver Solver
@ffi.Native<ffi.Void Function(ffi.Pointer<OSQPSolver>)>()
external void osqp_cold_start(ffi.Pointer<OSQPSolver> solver);

/// Return the error string for a given error code.
///
/// @param error_flag Error code to get description of
/// @return String describing the error code
@ffi.Native<ffi.Pointer<ffi.Char> Function(OSQPInt)>()
external ffi.Pointer<ffi.Char> osqp_error_message(int error_flag);

/// Return the number of variables and constraints
///
/// @param[in]  solver Solver
/// @param[out] m      Pointer to integer that will hold m
/// @param[out] n      Pointer to integer that will hold n
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPInt>,
    ffi.Pointer<OSQPInt>,
  )
>()
external void osqp_get_dimensions(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPInt> m,
  ffi.Pointer<OSQPInt> n,
);

/// Store the optimization problem result from solver \a solver into the solution
/// \a solution. Note that \a solution must already be allocated with the component
/// vectors the correct lengths.
///
/// @param  solver   Solver
/// @param  solution Solution object to store result in
/// @return          Error flag
@ffi.Native<
  OSQPInt Function(ffi.Pointer<OSQPSolver>, ffi.Pointer<OSQPSolution>)
>()
external int osqp_get_solution(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPSolution> solution,
);

/// Set default codegen define values.
///
/// @note The @c defines structure must already be allocated in memory.
///
/// @param defines Structure to set to default values.
@ffi.Native<ffi.Void Function(ffi.Pointer<OSQPCodegenDefines>)>()
external void osqp_set_default_codegen_defines(
  ffi.Pointer<OSQPCodegenDefines> defines,
);

/// Get the default settings from the osqp_api_constants.h file.
///
/// @note the @c settings parameter must already be allocated in memory.
///
/// @param settings Settings structure to populate
@ffi.Native<ffi.Void Function(ffi.Pointer<OSQPSettings>)>()
external void osqp_set_default_settings(ffi.Pointer<OSQPSettings> settings);

/// Initialize OSQP solver allocating memory.
///
/// It performs:
/// - data and settings validation
/// - problem data scaling
/// - setup linear system solver:
/// - direct solver: KKT matrix factorization is performed here
/// - indirect solver: reduced KKT matrix preconditioning is performed here
///
/// NB: This is the only function that allocates dynamic memory and is not used
/// during code generation
///
/// @param  solverp   Solver pointer
/// @param  P         Problem data (upper triangular part of quadratic cost term, csc format)
/// @param  q         Problem data (linear cost term)
/// @param  A         Problem data (constraint matrix, csc format)
/// @param  l         Problem data (constraint lower bound)
/// @param  u         Problem data (constraint upper bound)
/// @param  m         Problem data (number of constraints)
/// @param  n         Problem data (number of variables)
/// @param  settings  Solver settings
/// @return           Exitflag for errors (0 if no errors)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<ffi.Pointer<OSQPSolver>>,
    ffi.Pointer<OSQPCscMatrix>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPCscMatrix>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
    OSQPInt,
    OSQPInt,
    ffi.Pointer<OSQPSettings>,
  )
>()
external int osqp_setup(
  ffi.Pointer<ffi.Pointer<OSQPSolver>> solverp,
  ffi.Pointer<OSQPCscMatrix> P,
  ffi.Pointer<OSQPFloat> q,
  ffi.Pointer<OSQPCscMatrix> A,
  ffi.Pointer<OSQPFloat> l,
  ffi.Pointer<OSQPFloat> u,
  int m,
  int n,
  ffi.Pointer<OSQPSettings> settings,
);

/// Solve quadratic program
///
/// The final solver information is stored in the  \a solver->info  structure
///
/// The solution is stored in the  \a solver->solution  structure
///
/// If the problem is primal infeasible, the certificate is stored
/// in \a solver->delta_y
///
/// If the problem is dual infeasible, the certificate is stored in \a
/// solver->delta_x
///
/// @param  solver Solver
/// @return        Exitflag for errors (0 if no errors)
@ffi.Native<OSQPInt Function(ffi.Pointer<OSQPSolver>)>()
external int osqp_solve(ffi.Pointer<OSQPSolver> solver);

/// Update elements of matrices P (upper triangular) and A by preserving
/// their sparsity structures.
///
/// If Px_new_idx (Ax_new_idx) is OSQP_NULL, Px_new (Ax_new) is assumed
/// to be as long as P->x (A->x) and the whole P->x (A->x) is replaced.
///
/// @param  solver     Solver
/// @param  Px_new     Vector of new elements in P->x (upper triangular), NULL if none
/// @param  Px_new_idx Index mapping new elements to positions in P->x
/// @param  P_new_n    Number of new elements to be changed
/// @param  Ax_new     Vector of new elements in A->x, NULL if none
/// @param  Ax_new_idx Index mapping new elements to positions in A->x
/// @param  A_new_n    Number of new elements to be changed
/// @return            output flag:  0: OK
/// 1: P_new_n > nnzP
/// 2: A_new_n > nnzA
/// <0: error in the update
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPInt>,
    OSQPInt,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPInt>,
    OSQPInt,
  )
>()
external int osqp_update_data_mat(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPFloat> Px_new,
  ffi.Pointer<OSQPInt> Px_new_idx,
  int P_new_n,
  ffi.Pointer<OSQPFloat> Ax_new,
  ffi.Pointer<OSQPInt> Ax_new_idx,
  int A_new_n,
);

/// Update problem data vectors
/// @param  solver  Solver
/// @param  q_new   New linear cost, NULL if none
/// @param  l_new   New lower bound, NULL if none
/// @param  u_new   New upper bound, NULL if none
/// @return         Exitflag for errors (0 if no errors)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
  )
>()
external int osqp_update_data_vec(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPFloat> q_new,
  ffi.Pointer<OSQPFloat> l_new,
  ffi.Pointer<OSQPFloat> u_new,
);

/// Update the ADMM parameter rho.
///
/// Limit it between OSQP_RHO_MIN and OSQP_RHO_MAX.
///
/// @param  solver  Solver
/// @param  rho_new New rho value
/// @return         Exitflag for errors (0 if no errors)
@ffi.Native<OSQPInt Function(ffi.Pointer<OSQPSolver>, OSQPFloat)>()
external int osqp_update_rho(ffi.Pointer<OSQPSolver> solver, double rho_new);

/// Update settings in @c solver with the new settings from @c new_settings.
///
/// The following settings can only be set at problem setup time through @c osqp_setup and are ignored
/// in this function:
/// - scaling
/// - rho_is_vec
/// - sigma
/// - adaptive_rho
/// - adaptive_rho_interval
/// - adaptive_rho_fraction
/// - adaptive_rho_tolerance
///
/// The rho setting must be updated using @c osqp_update_rho, and is ignored by this function.
///
/// @note Every setting from @c new_settings is copied to @c solver.
///
/// @param  solver       Solver
/// @param  new_settings New solver settings
/// @return              Exitflag for errors (0 if no errors)
@ffi.Native<
  OSQPInt Function(ffi.Pointer<OSQPSolver>, ffi.Pointer<OSQPSettings>)
>()
external int osqp_update_settings(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPSettings> new_settings,
);

/// Return OSQP version
///
/// @return OSQP version string
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> osqp_version();

/// Warm start primal and dual variables
/// @param  solver Solver
/// @param  x      Primal variable, NULL if none
/// @param  y      Dual variable, NULL if none
/// @return        Exitflag for errors (0 if no errors)
@ffi.Native<
  OSQPInt Function(
    ffi.Pointer<OSQPSolver>,
    ffi.Pointer<OSQPFloat>,
    ffi.Pointer<OSQPFloat>,
  )
>()
external int osqp_warm_start(
  ffi.Pointer<OSQPSolver> solver,
  ffi.Pointer<OSQPFloat> x,
  ffi.Pointer<OSQPFloat> y,
);

/// Structure to hold the settings for the generated code
final class OSQPCodegenDefines extends ffi.Struct {
  /// < Embedded mode (1 = vector update, 2 = vector + matrix update)
  @OSQPInt()
  external int embedded_mode;

  /// < Use floats if 1, doubles if 0
  @OSQPInt()
  external int float_type;

  /// < Enable printing if 1
  @OSQPInt()
  external int printing_enable;

  /// < Enable timing of code sections if 1
  @OSQPInt()
  external int profiling_enable;

  /// < Enable interrupt checking if 1
  @OSQPInt()
  external int interrupt_enable;

  /// < Enable deriatives if 1
  @OSQPInt()
  external int derivatives_enable;

  static ffi.Pointer<OSQPCodegenDefines> $allocate(
    ffi.Allocator $allocator, {
    required int embedded_mode,
    required int float_type,
    required int printing_enable,
    required int profiling_enable,
    required int interrupt_enable,
    required int derivatives_enable,
  }) => $allocator<OSQPCodegenDefines>()
    ..ref.embedded_mode = embedded_mode
    ..ref.float_type = float_type
    ..ref.printing_enable = printing_enable
    ..ref.profiling_enable = profiling_enable
    ..ref.interrupt_enable = interrupt_enable
    ..ref.derivatives_enable = derivatives_enable;
}

/// Matrix in compressed-column form.
/// The structure is used internally to store matrices in the triplet form as well,
/// but the API requires that the matrices are in the CSC format.
final class OSQPCscMatrix extends ffi.Struct {
  /// < number of rows
  @OSQPInt()
  external int m;

  /// < number of columns
  @OSQPInt()
  external int n;

  /// < column pointers (size n+1); col indices (size nzmax) starting from 0 for triplet format
  external ffi.Pointer<OSQPInt> p;

  /// < row indices, size nzmax starting from 0
  external ffi.Pointer<OSQPInt> i;

  /// < numerical values, size nzmax
  external ffi.Pointer<OSQPFloat> x;

  /// < maximum number of entries
  @OSQPInt()
  external int nzmax;

  /// < number of entries in triplet matrix, -1 for csc
  @OSQPInt()
  external int nz;

  /// < 1 if the p, i and x pointers were allocated automatically, 0 if they are owned by the user
  @OSQPInt()
  external int owned;

  static ffi.Pointer<OSQPCscMatrix> $allocate(
    ffi.Allocator $allocator, {
    required int m,
    required int n,
    required ffi.Pointer<OSQPInt> p,
    required ffi.Pointer<OSQPInt> i,
    required ffi.Pointer<OSQPFloat> x,
    required int nzmax,
    required int nz,
    required int owned,
  }) => $allocator<OSQPCscMatrix>()
    ..ref.m = m
    ..ref.n = n
    ..ref.p = p
    ..ref.i = i
    ..ref.x = x
    ..ref.nzmax = nzmax
    ..ref.nz = nz
    ..ref.owned = owned;
}

typedef OSQPFloat = ffi.Double;
typedef DartOSQPFloat = double;

/// Information about the solution process.
final class OSQPInfo extends ffi.Struct {
  /// < Status string, e.g. 'solved'
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> status;

  /// < Status as OSQPInt, defined in osqp_api_constants.h
  @OSQPInt()
  external int status_val;

  /// < Polishing status: successful (1), unperformed (0), unsuccessful (-1)
  @OSQPInt()
  external int status_polish;

  /// < Primal objective value
  @OSQPFloat()
  external double obj_val;

  /// < Dual objective value
  @OSQPFloat()
  external double dual_obj_val;

  /// < Norm of primal residual
  @OSQPFloat()
  external double prim_res;

  /// < Norm of dual residual
  @OSQPFloat()
  external double dual_res;

  /// < Duality gap (Primal obj - Dual obj)
  @OSQPFloat()
  external double duality_gap;

  /// < Number of iterations taken
  @OSQPInt()
  external int iter;

  /// < Number of rho updates performned
  @OSQPInt()
  external int rho_updates;

  /// < Best rho estimate so far from residuals
  @OSQPFloat()
  external double rho_estimate;

  /// < Setup phase time (seconds)
  @OSQPFloat()
  external double setup_time;

  /// < Solve phase time (seconds)
  @OSQPFloat()
  external double solve_time;

  /// < Update phase time (seconds)
  @OSQPFloat()
  external double update_time;

  /// < Polish phase time (seconds)
  @OSQPFloat()
  external double polish_time;

  /// < Total solve time (seconds)
  @OSQPFloat()
  external double run_time;

  /// < Integral of duality gap over time (Primal-dual integral), requires profiling
  @OSQPFloat()
  external double primdual_int;

  /// < Relative KKT error
  @OSQPFloat()
  external double rel_kkt_error;
}

typedef OSQPInt = ffi.LongLong;
typedef DartOSQPInt = int;

/// User settings
final class OSQPSettings extends ffi.Struct {
  /// < device identifier; currently used for CUDA devices
  @OSQPInt()
  external int device;

  /// < linear system solver to use
  @ffi.UnsignedInt()
  external int linsys_solverAsInt;

  osqp_linsys_solver_type get linsys_solver =>
      osqp_linsys_solver_type.fromValue(linsys_solverAsInt);
  set linsys_solver(osqp_linsys_solver_type value) =>
      linsys_solverAsInt = value.value;

  /// < boolean; allocate solution in OSQPSolver during osqp_setup
  @OSQPInt()
  external int allocate_solution;

  /// < boolean; write out progress
  @OSQPInt()
  external int verbose;

  /// < integer; level of detail for profiler annotations
  @OSQPInt()
  external int profiler_level;

  /// < boolean; warm start
  @OSQPInt()
  external int warm_starting;

  /// < data scaling iterations; if 0, then disabled
  @OSQPInt()
  external int scaling;

  /// < boolean; polish ADMM solution
  @OSQPInt()
  external int polishing;

  /// < ADMM penalty parameter
  @OSQPFloat()
  external double rho;

  /// < boolean; is rho scalar or vector?
  @OSQPInt()
  external int rho_is_vec;

  /// < ADMM penalty parameter
  @OSQPFloat()
  external double sigma;

  /// < ADMM relaxation parameter
  @OSQPFloat()
  external double alpha;

  /// < maximum number of CG iterations per solve
  @OSQPInt()
  external int cg_max_iter;

  /// < number of consecutive zero CG iterations before the tolerance gets halved
  @OSQPInt()
  external int cg_tol_reduction;

  /// < CG tolerance (fraction of ADMM residuals)
  @OSQPFloat()
  external double cg_tol_fraction;

  /// < Preconditioner to use in the CG method
  @ffi.UnsignedInt()
  external int cg_precondAsInt;

  osqp_precond_type get cg_precond =>
      osqp_precond_type.fromValue(cg_precondAsInt);
  set cg_precond(osqp_precond_type value) => cg_precondAsInt = value.value;

  /// rho stepsize adaption method
  @OSQPInt()
  external int adaptive_rho;

  /// Interval between rho adaptations
  ///
  /// When adaptive_rho == OSQP_ADAPTIVE_RHO_UPDATE_ITERATIONS, this is the number of iterations
  /// between rho updates.
  ///
  /// Not used when adaptive_rho is any other value.
  @OSQPInt()
  external int adaptive_rho_interval;

  /// Adaptation parameter controlling when non-fixed rho adaptations occur.
  ///
  /// - When adaptive_rho == OSQP_ADAPTIVE_RHO_UPDATE_TIME, this is the fraction of the
  /// setup time to use as the rho adaptation interval.
  /// - When adaptive_rho == OSQP_ADAPTIVE_RHO_UPDATE_KKT_ERROR, this is the fraction of
  /// the previous KKT error to adapt rho at.
  /// - Not used for any other adaptive_rho value.
  @OSQPFloat()
  external double adaptive_rho_fraction;

  /// Tolerance applied when adapting rho.
  ///
  /// New rho must be X times larger or smaller than the current one to change it
  @OSQPFloat()
  external double adaptive_rho_tolerance;

  /// < maximum number of iterations
  @OSQPInt()
  external int max_iter;

  /// < absolute solution tolerance
  @OSQPFloat()
  external double eps_abs;

  /// < relative solution tolerance
  @OSQPFloat()
  external double eps_rel;

  /// < primal infeasibility tolerance
  @OSQPFloat()
  external double eps_prim_inf;

  /// < dual infeasibility tolerance
  @OSQPFloat()
  external double eps_dual_inf;

  /// < boolean; use scaled termination criteria
  @OSQPInt()
  external int scaled_termination;

  /// < integer, check termination interval; if 0, checking is disabled
  @OSQPInt()
  external int check_termination;

  /// < Boolean; use duality gap termination criteria
  @OSQPInt()
  external int check_dualgap;

  /// < maximum time to solve the problem (seconds)
  @OSQPFloat()
  external double time_limit;

  /// < regularization parameter for polishing
  @OSQPFloat()
  external double delta;

  /// < number of iterative refinement steps in polishing
  @OSQPInt()
  external int polish_refine_iter;

  static ffi.Pointer<OSQPSettings> $allocate(
    ffi.Allocator $allocator, {
    required int device,
    required osqp_linsys_solver_type linsys_solver,
    required int allocate_solution,
    required int verbose,
    required int profiler_level,
    required int warm_starting,
    required int scaling,
    required int polishing,
    required double rho,
    required int rho_is_vec,
    required double sigma,
    required double alpha,
    required int cg_max_iter,
    required int cg_tol_reduction,
    required double cg_tol_fraction,
    required osqp_precond_type cg_precond,
    required int adaptive_rho,
    required int adaptive_rho_interval,
    required double adaptive_rho_fraction,
    required double adaptive_rho_tolerance,
    required int max_iter,
    required double eps_abs,
    required double eps_rel,
    required double eps_prim_inf,
    required double eps_dual_inf,
    required int scaled_termination,
    required int check_termination,
    required int check_dualgap,
    required double time_limit,
    required double delta,
    required int polish_refine_iter,
  }) => $allocator<OSQPSettings>()
    ..ref.device = device
    ..ref.linsys_solver = linsys_solver
    ..ref.allocate_solution = allocate_solution
    ..ref.verbose = verbose
    ..ref.profiler_level = profiler_level
    ..ref.warm_starting = warm_starting
    ..ref.scaling = scaling
    ..ref.polishing = polishing
    ..ref.rho = rho
    ..ref.rho_is_vec = rho_is_vec
    ..ref.sigma = sigma
    ..ref.alpha = alpha
    ..ref.cg_max_iter = cg_max_iter
    ..ref.cg_tol_reduction = cg_tol_reduction
    ..ref.cg_tol_fraction = cg_tol_fraction
    ..ref.cg_precond = cg_precond
    ..ref.adaptive_rho = adaptive_rho
    ..ref.adaptive_rho_interval = adaptive_rho_interval
    ..ref.adaptive_rho_fraction = adaptive_rho_fraction
    ..ref.adaptive_rho_tolerance = adaptive_rho_tolerance
    ..ref.max_iter = max_iter
    ..ref.eps_abs = eps_abs
    ..ref.eps_rel = eps_rel
    ..ref.eps_prim_inf = eps_prim_inf
    ..ref.eps_dual_inf = eps_dual_inf
    ..ref.scaled_termination = scaled_termination
    ..ref.check_termination = check_termination
    ..ref.check_dualgap = check_dualgap
    ..ref.time_limit = time_limit
    ..ref.delta = delta
    ..ref.polish_refine_iter = polish_refine_iter;
}

/// Structure to hold the computed solution (if any), and any certificates of
/// infeasibility (if any) found by the solver.
final class OSQPSolution extends ffi.Struct {
  /// < Primal solution
  external ffi.Pointer<OSQPFloat> x;

  /// < Lagrange multiplier associated with \f$l \le Ax \le u\f$
  external ffi.Pointer<OSQPFloat> y;

  /// < Primal infeasibility certificate
  external ffi.Pointer<OSQPFloat> prim_inf_cert;

  /// < Dual infeasibility certificate
  external ffi.Pointer<OSQPFloat> dual_inf_cert;

  static ffi.Pointer<OSQPSolution> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<OSQPFloat> x,
    required ffi.Pointer<OSQPFloat> y,
    required ffi.Pointer<OSQPFloat> prim_inf_cert,
    required ffi.Pointer<OSQPFloat> dual_inf_cert,
  }) => $allocator<OSQPSolution>()
    ..ref.x = x
    ..ref.y = y
    ..ref.prim_inf_cert = prim_inf_cert
    ..ref.dual_inf_cert = dual_inf_cert;
}

/// Main OSQP solver structure that holds all information.
final class OSQPSolver extends ffi.Struct {
  /// < Problem settings
  external ffi.Pointer<OSQPSettings> settings;

  /// < Computed solution
  external ffi.Pointer<OSQPSolution> solution;

  /// < Solver information
  external ffi.Pointer<OSQPInfo> info;

  /// < Internal solver workspace (contents not public)
  external ffi.Pointer<OSQPWorkspace> work;

  static ffi.Pointer<OSQPSolver> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<OSQPSettings> settings,
    required ffi.Pointer<OSQPSolution> solution,
    required ffi.Pointer<OSQPInfo> info,
    required ffi.Pointer<OSQPWorkspace> work,
  }) => $allocator<OSQPSolver>()
    ..ref.settings = settings
    ..ref.solution = solution
    ..ref.info = info
    ..ref.work = work;
}

typedef OSQPWorkspace = OSQPWorkspace_;

final class OSQPWorkspace_ extends ffi.Opaque {}

const int OSQP_ADAPTIVE_RHO_FIXED = 100;

const double OSQP_ADAPTIVE_RHO_FRACTION = 0.4;

const int OSQP_ADAPTIVE_RHO_INTERVAL = 50;

const int OSQP_ADAPTIVE_RHO_MULTIPLE_TERMINATION = 4;

const double OSQP_ADAPTIVE_RHO_TOLERANCE = 5.0;

const int OSQP_ADAPTIVE_RHO_UPDATE_DEFAULT = 1;

const int OSQP_ADAPTIVE_RHO_UPDATE_DISABLED = 0;

const int OSQP_ADAPTIVE_RHO_UPDATE_ITERATIONS = 1;

const int OSQP_ADAPTIVE_RHO_UPDATE_KKT_ERROR = 3;

const int OSQP_ADAPTIVE_RHO_UPDATE_TIME = 2;

const double OSQP_ALPHA = 1.6;

const int OSQP_CG_MAX_ITER = 20;

const double OSQP_CG_POLISH_TOL = 0.00001;

const double OSQP_CG_TOL_FRACTION = 0.15;

const double OSQP_CG_TOL_MIN = 1e-7;

const int OSQP_CG_TOL_REDUCTION = 10;

const int OSQP_CHECK_DUALGAP = 1;

const int OSQP_CHECK_TERMINATION = 25;

const double OSQP_DELTA = 0.000001;

const double OSQP_DIVISION_TOL = 9.999999999999999e-31;

const double OSQP_EPS_ABS = 0.001;

const double OSQP_EPS_DUAL_INF = 0.0001;

const double OSQP_EPS_PRIM_INF = 0.0001;

const double OSQP_EPS_REL = 0.001;

const double OSQP_INFTY = 1e+30;

const int OSQP_MAX_ITER = 4000;

const double OSQP_MAX_SCALING = 10000.0;

const double OSQP_MIN_SCALING = 0.0001;

const double OSQP_NAN = 2143289344.0;

const int OSQP_NULL = 0;

const int OSQP_POLISHING = 0;

const int OSQP_POLISH_REFINE_ITER = 3;

const int OSQP_PRINT_INTERVAL = 200;

const double OSQP_RHO = 0.1;

const double OSQP_RHO_EQ_OVER_RHO_INEQ = 1000.0;

const int OSQP_RHO_IS_VEC = 1;

const double OSQP_RHO_MAX = 1000000.0;

const double OSQP_RHO_MIN = 0.000001;

const double OSQP_RHO_TOL = 0.0001;

const int OSQP_SCALED_TERMINATION = 0;

const int OSQP_SCALING = 10;

const double OSQP_SIGMA = 0.000001;

const double OSQP_TIME_LIMIT = 10000000000.0;

const int OSQP_VERBOSE = 1;

const int OSQP_WARM_STARTING = 1;

const double OSQP_ZERO_DEADZONE = 1e-15;

/// Solver capabilities *
/// /
/// /**
/// Flags used to represent what capabilities the compiled OSQP solver has.
///
/// These flags are used as bit flags, so capabilities can be tested using bit-wise operations.
enum osqp_capabilities_type {
  /// << A direct linear solver is present in the algebra.
  OSQP_CAPABILITY_DIRECT_SOLVER(1),

  /// << An indirect linear solver is present in the algebra.
  OSQP_CAPABILITY_INDIRECT_SOLVER(2),

  /// << Code generation is present.
  OSQP_CAPABILITY_CODEGEN(4),

  /// << The problem matrices can be updated.
  OSQP_CAPABILITY_UPDATE_MATRICES(8),

  /// << Solution derivatives w.r.t P/q/A/l/u are available.
  OSQP_CAPABILITY_DERIVATIVES(16);

  final int value;
  const osqp_capabilities_type(this.value);

  static osqp_capabilities_type fromValue(int value) => switch (value) {
    1 => OSQP_CAPABILITY_DIRECT_SOLVER,
    2 => OSQP_CAPABILITY_INDIRECT_SOLVER,
    4 => OSQP_CAPABILITY_CODEGEN,
    8 => OSQP_CAPABILITY_UPDATE_MATRICES,
    16 => OSQP_CAPABILITY_DERIVATIVES,
    _ => throw ArgumentError(
      'Unknown value for osqp_capabilities_type: $value',
    ),
  };
}

/// Solver Errors  *
enum osqp_error_type {
  OSQP_NO_ERROR(0),
  OSQP_DATA_VALIDATION_ERROR(1),
  OSQP_SETTINGS_VALIDATION_ERROR(2),
  OSQP_LINSYS_SOLVER_INIT_ERROR(3),
  OSQP_NONCVX_ERROR(4),
  OSQP_MEM_ALLOC_ERROR(5),
  OSQP_WORKSPACE_NOT_INIT_ERROR(6),
  OSQP_ALGEBRA_LOAD_ERROR(7),
  OSQP_FOPEN_ERROR(8),
  OSQP_CODEGEN_DEFINES_ERROR(9),
  OSQP_DATA_NOT_INITIALIZED(10),

  /// < Function not implemented in this library
  OSQP_FUNC_NOT_IMPLEMENTED(11),
  OSQP_LAST_ERROR_PLACE(12);

  final int value;
  const osqp_error_type(this.value);

  static osqp_error_type fromValue(int value) => switch (value) {
    0 => OSQP_NO_ERROR,
    1 => OSQP_DATA_VALIDATION_ERROR,
    2 => OSQP_SETTINGS_VALIDATION_ERROR,
    3 => OSQP_LINSYS_SOLVER_INIT_ERROR,
    4 => OSQP_NONCVX_ERROR,
    5 => OSQP_MEM_ALLOC_ERROR,
    6 => OSQP_WORKSPACE_NOT_INIT_ERROR,
    7 => OSQP_ALGEBRA_LOAD_ERROR,
    8 => OSQP_FOPEN_ERROR,
    9 => OSQP_CODEGEN_DEFINES_ERROR,
    10 => OSQP_DATA_NOT_INITIALIZED,
    11 => OSQP_FUNC_NOT_IMPLEMENTED,
    12 => OSQP_LAST_ERROR_PLACE,
    _ => throw ArgumentError('Unknown value for osqp_error_type: $value'),
  };
}

/// Linear System Solvers *
enum osqp_linsys_solver_type {
  OSQP_UNKNOWN_SOLVER(0),
  OSQP_DIRECT_SOLVER(1),
  OSQP_INDIRECT_SOLVER(2);

  final int value;
  const osqp_linsys_solver_type(this.value);

  static osqp_linsys_solver_type fromValue(int value) => switch (value) {
    0 => OSQP_UNKNOWN_SOLVER,
    1 => OSQP_DIRECT_SOLVER,
    2 => OSQP_INDIRECT_SOLVER,
    _ => throw ArgumentError(
      'Unknown value for osqp_linsys_solver_type: $value',
    ),
  };
}

/// Polish Status  *
enum osqp_polish_status_type {
  OSQP_POLISH_LINSYS_ERROR(-2),
  OSQP_POLISH_FAILED(-1),
  OSQP_POLISH_NOT_PERFORMED(0),
  OSQP_POLISH_SUCCESS(1),
  OSQP_POLISH_NO_ACTIVE_SET_FOUND(2);

  final int value;
  const osqp_polish_status_type(this.value);

  static osqp_polish_status_type fromValue(int value) => switch (value) {
    -2 => OSQP_POLISH_LINSYS_ERROR,
    -1 => OSQP_POLISH_FAILED,
    0 => OSQP_POLISH_NOT_PERFORMED,
    1 => OSQP_POLISH_SUCCESS,
    2 => OSQP_POLISH_NO_ACTIVE_SET_FOUND,
    _ => throw ArgumentError(
      'Unknown value for osqp_polish_status_type: $value',
    ),
  };
}

/// Preconditioners for CG method *
enum osqp_precond_type {
  OSQP_NO_PRECONDITIONER(0),
  OSQP_DIAGONAL_PRECONDITIONER(1);

  final int value;
  const osqp_precond_type(this.value);

  static osqp_precond_type fromValue(int value) => switch (value) {
    0 => OSQP_NO_PRECONDITIONER,
    1 => OSQP_DIAGONAL_PRECONDITIONER,
    _ => throw ArgumentError('Unknown value for osqp_precond_type: $value'),
  };
}

/// Solver Status  *
enum osqp_status_type {
  OSQP_SOLVED(1),
  OSQP_SOLVED_INACCURATE(2),
  OSQP_PRIMAL_INFEASIBLE(3),
  OSQP_PRIMAL_INFEASIBLE_INACCURATE(4),
  OSQP_DUAL_INFEASIBLE(5),
  OSQP_DUAL_INFEASIBLE_INACCURATE(6),
  OSQP_MAX_ITER_REACHED(7),
  OSQP_TIME_LIMIT_REACHED(8),
  OSQP_NON_CVX(9),
  OSQP_SIGINT(10),
  OSQP_UNSOLVED(11);

  final int value;
  const osqp_status_type(this.value);

  static osqp_status_type fromValue(int value) => switch (value) {
    1 => OSQP_SOLVED,
    2 => OSQP_SOLVED_INACCURATE,
    3 => OSQP_PRIMAL_INFEASIBLE,
    4 => OSQP_PRIMAL_INFEASIBLE_INACCURATE,
    5 => OSQP_DUAL_INFEASIBLE,
    6 => OSQP_DUAL_INFEASIBLE_INACCURATE,
    7 => OSQP_MAX_ITER_REACHED,
    8 => OSQP_TIME_LIMIT_REACHED,
    9 => OSQP_NON_CVX,
    10 => OSQP_SIGINT,
    11 => OSQP_UNSOLVED,
    _ => throw ArgumentError('Unknown value for osqp_status_type: $value'),
  };
}
